<?php
/**
 * @file
 * Module file for views_infinite_scroll.
 */

/**
 * Implements hook_preprocess_views_infinite_scroll_pager().
 */
function views_infinite_scroll_preprocess_views_infinite_scroll_pager(&$vars) {
  // @todo, find out if there is a better way to model our pager off the mini
  // one.
  template_preprocess_views_mini_pager($vars);
}

/**
 * Load the VIS library information.
 */
function views_infinite_scroll_autopager_library() {
  $library_discovery = \Drupal::service('library.discovery');
  return $library_discovery->getLibraryByName('views_infinite_scroll', 'jquery.autopager');
}
